

[#container]
== Container

A collection of ordered blocks that the learner can navigate through.

[discrete]
=== Parameters

[cols="1,1,1,1"]
|===
| Name | Type | Description | Required
| `id` | <<pathContainerId, `PathContainerId`>> | Identifier of the container | Yes
| `name` | https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Data.md#42-language-maps[LanguageMap] | Name of the container | Yes
| `activity` | https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Data.md#activity-definition[Activity]  | Activity of the container | No
| `unitCompletion` | boolean | If true, the unit will be considered complete when the  container is done | No
| `blocks` | xref:block.adoc#block[`Block`] `array`  | Blocks of the container | Yes
|===

[discrete]
=== Restrictions

There **must** be at least one xref:block.adoc#block[`Block`] in the `blocks` array.

In the xref:unit.adoc#unit[`Unit`], there **must** be at least one xref:container.adoc#container[`Container`] with `unitCompletion` set to `true`.

[discrete]
=== Details 

A container can be directly within the unit or within a path.

If the container is directly within the unit, an implementation **should** display the `name` of the container in the navigation. If the container is within a path which is displayed in the navigation, the `name` of the container **should** be displayed as a sub-item of the path.

If `activity` is undefined, no statements about the container will be sent to the LRS, however, blocks within the container **may** still send statements.

A container is considered done when all of its blocks are done. Once a container is done it cannot be undone.

Once a container is done, an implementation **must** allow the learner to navigate to the next container in the unit. An implementation **may** also allow the learner to navigate to the next container before the current container is done.


[#pathContainerId]
=== PathContainerId

A human readable string ID that uniquely identifies a container.

==== Restrictions

The `pathContainerId` **must**:

- be a URI prefixed with `containers/`
- be unique in the unit
- only contain characters that are allowed in a URI but do not have a reserved purpose (as defined in RFC 3986)