[#path]
== Path

A path is a collection of ordered containers that a learner can navigate through.

[discrete]
=== Parameters

All paths have the following parameters:

[cols="1,1,1,1"]
|===
| Name | Type | Description | Required
| `id` | <<pathId, `PathID`>> | Identifier of the `Path` | Yes
| `name` | https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Data.md#42-language-maps[LanguageMap] | Name of the path | No
| `activity` | https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Data.md#activity-definition[Activity]| Activity of the path | No
| `containers` | xref:container.adoc#container[`Container`]`array` | Containers of the path | Yes
|===

[discrete]
=== Restrictions

A path **must** contain at least one xref:container.adoc#container[`Container`].

[discrete]
=== Details

If `name` is defined, an implementation **should** provide a way for the learner to navigate to the path.
If `name` is undefined, an implementation **should** only allow navigation to the path via a xref:block.adoc#
button[`Button`].

If `activity` is undefined, no statements about the path will be sent to the LRS, however, containers and blocks may still send statements.

An implementation **should** display the containers in the order they are defined in the `containers` array.

[#pathId]
=== PathId

A human readable string ID that uniquely identifies a path.

==== Restrictions

The `pathId` **must**:

- be a URI prefixed with `paths/`
- be unique in the unit
- only contain characters that are allowed in a URI but do not have a reserved purpose (as defined in RFC 3986)

=== Examples

==== Path definition

A minimum path definition has the following properties:
`id` and `containers`.

[source,json]
----
{
   "id":"paths/advanced-atmospheric-circulation",
   "name":{
      "en":"Advanced Atmospheric Circulation"
   },
   "activity":{
      "id":"http://example.com/introduction-to-atmospheric-circulation/advanced-atmospheric-circulation"
   },
   "containers":[
      {
         "id":"containers/section1",
         "name":{
            "en":"Section 1"
         },
         "blocks":[
            {
               "type":"html",
               "url":"data/section1/header.html"
            }
         ],
         "unitCompletion":false
      }
   ]
};
----